### PR TITLE
Add Appsignal instrumentation

### PR DESCRIPTION
**Pull request by timraasveld**
image

### CODE REVIEW

**Comment by timraasveld** [comment]
I believe failing Circle tests are beyond scope of this PR

**Comment by daandavidsz** [comment]
Is that really the case? It seems you can't see at this moment if the specs have run successfully or not.

**Comment by hampei** [comment]
idd, zou zeggen fix master, en rebase

**Comment by timraasveld** [comment]
@daandavidsz you're right.

For now we decided not to include Appsignal-specific logic in the OpenCPU gem.

**Pull request closed without merging**
